---

additional_packages:
  - build-essential
  - python-dev
  - python-openssl
  - git

meteoUpdatePicturesPath: /home/pi/meteoUpdatePictures

DHT22:
  present: true
  pin: 23
  path: /home/pi/dht22
  delay: 20
  samples_size: 10
  #3 \ÂºC
  measure_allowed_desviation: 1
